
apiVersion: v1
kind: ConfigMap
metadata:
  name: democracy-api-config
data:
  BUNDESTAGIO_SERVER_URL: http://bundestagio-srv:3100/
  DB_URL: mongodb://democracy-mongo:27017/democracy
  DEBUG: "true"
  GRAPHIQL: "true"
  NODE_ENV: development
  SMS_SIMULATE: "true"
  SMS_VERIFICATION: "false"
  STAGE: internal
  LOGGING_CONSOLE: silly
  # JWT
  AUTH_JWT_SECRET: CHANGE_ME
  AUTH_JWT_TTL: 1m
  AUTH_JWT_REFRESH_TTL: 5m
  JWT_BACKWARD_COMPATIBILITY: "true"