name: Release

on:
  workflow_dispatch:
    inputs:
      dryRun:
        description: 'Dry Run'
        required: true
        default: 'true'
      releaseVersion:
        description: 'Custom Version (major.minor.patch; leave empty for automatic determination)'
        required: false

jobs:
  create-new-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Configure Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
      - name: Bump and Commit
        run: |
          yarn run release
          git push --follow-tags

  push:
    needs: create-new-release
    runs-on: ubuntu-latest
    environment: docker
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Get version from package.json
      - name: Get version from package.json
        id: version
        run: echo ::set-output name=version::$(cat package.json | jq -r '.version')

      # Build the Docker image
      - name: Build Docker image
        run: docker build -t democracy-api:${{ steps.version.outputs.version }} .

      # Push the image to Docker Hub
      - name: Push image to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: docker.io
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push to Docker Hub
        run: docker push democracy-api:${{ steps.version.outputs.version }}