name: Release

on:
  workflow_dispatch:

jobs:
  create-new-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 
      - uses: actions/setup-node@v3
        with:
          node-version: 14
      - name: Configure Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
      - name: Bump and Commit
        run: |
          npx standard-version
          git push --follow-tags

  push:
    needs: create-new-release
    runs-on: ubuntu-latest
    environment: docker
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Get version from package.json
      - name: Get version from package.json
        id: version
        run: echo "version=$(cat package.json | jq -r '.version')" >> $GITHUB_OUTPUT

      # Build the Docker image
      - name: Build Docker image
        run: docker build  --cache-from democracy/democracy-server:latest -t democracy/democracy-server:${{ steps.version.outputs.version }} .

      # Push the image to Docker Hub
      - name: Push image to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push to Docker Hub
        run: |
          docker tag democracy/democracy-server:${{ steps.version.outputs.version }} democracy/democracy-server:latest
          docker push democracy/democracy-server:latest
          docker push democracy/democracy-server:${{ steps.version.outputs.version }}